language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

script: 
  - rm -rf /usr/local/Cellar/cmake
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get install -y cmake
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..
  - make
  - make test;
