language: cpp
before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get install cmake

script: 
  - cd build
  - cmake ..
  - make
  - make test;
